// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfFXRlbCmsVZya5grtw-4mKsyy8MDTT6g',
    appId: '1:828990764763:web:06bdd77a40be155386fefe',
    messagingSenderId: '828990764763',
    projectId: 'vcare-85101',
    authDomain: 'vcare-85101.firebaseapp.com',
    storageBucket: 'vcare-85101.firebasestorage.app',
    measurementId: 'G-LD25P669H0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwL-ngkwQqNltteQsRCYBbkdCVLn4See4',
    appId: '1:828990764763:android:7c470e1d2c6d1bb286fefe',
    messagingSenderId: '828990764763',
    projectId: 'vcare-85101',
    storageBucket: 'vcare-85101.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiagOP1lnVuhF-IBxbjlH6mY0By4qA_Aw',
    appId: '1:828990764763:ios:ea28ae31e3443fb986fefe',
    messagingSenderId: '828990764763',
    projectId: 'vcare-85101',
    storageBucket: 'vcare-85101.firebasestorage.app',
    iosBundleId: 'com.example.rotiPlanta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiagOP1lnVuhF-IBxbjlH6mY0By4qA_Aw',
    appId: '1:828990764763:ios:ea28ae31e3443fb986fefe',
    messagingSenderId: '828990764763',
    projectId: 'vcare-85101',
    storageBucket: 'vcare-85101.firebasestorage.app',
    iosBundleId: 'com.example.rotiPlanta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfFXRlbCmsVZya5grtw-4mKsyy8MDTT6g',
    appId: '1:828990764763:web:ef6bc4df956b353486fefe',
    messagingSenderId: '828990764763',
    projectId: 'vcare-85101',
    authDomain: 'vcare-85101.firebaseapp.com',
    storageBucket: 'vcare-85101.firebasestorage.app',
    measurementId: 'G-B9BT1JT62G',
  );
}
